"""Add timezone to chat_threads

Revision ID: 280e15765d80
Revises: e4a2b3c4d5e6
Create Date: 2026-02-19 22:10:34.787567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '280e15765d80'
down_revision: Union[str, None] = 'e4a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Update existing NULLs to 'now' so that the NOT NULL constraint does not fail
    op.execute("UPDATE chat_threads SET created_at = NOW() WHERE created_at IS NULL")
    op.alter_column('chat_threads', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.execute("UPDATE chat_threads SET updated_at = NOW() WHERE updated_at IS NULL")
    op.alter_column('chat_threads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.drop_constraint(op.f('chat_threads_user_id_fkey'), 'chat_threads', type_='foreignkey')
    op.create_foreign_key(None, 'chat_threads', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_document_chunks_embedding_hnsw'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_document_chunks_embedding_hnsw'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_constraint(None, 'chat_threads', type_='foreignkey')
    op.create_foreign_key(op.f('chat_threads_user_id_fkey'), 'chat_threads', 'users', ['user_id'], ['id'])
    op.alter_column('chat_threads', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('chat_threads', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
