"""add row_count and data to chat_messages

Revision ID: 9fac960e2063
Revises: 71d928dc7852
Create Date: 2026-02-20 00:32:46.254653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fac960e2063'
down_revision: Union[str, None] = '71d928dc7852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('row_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('chat_messages', sa.Column('data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'data')
    op.drop_column('chat_messages', 'row_count')
    # ### end Alembic commands ###
